# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='time_stamp',
            field=models.DateTimeField(),
        ),
    ]
