# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-10 23:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0003_peer'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='peer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chain.Peer'),
            preserve_default=False,
        ),
    ]
