# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0006_auto_20170511_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='salt',
            field=models.CharField(default='', max_length=255),
        ),
    ]
