# Generated by Django 2.0.1 on 2018-01-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0007_block_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='salt',
        ),
        migrations.AddField(
            model_name='block',
            name='nonce',
            field=models.CharField(default='', max_length=255),
        ),
    ]
