# Generated by Django 2.0.1 on 2018-01-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0008_auto_20180116_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=200)),
                ('receiver', models.CharField(max_length=200)),
                ('amount', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('added_to_block', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='salt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='hash',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='block',
            name='index',
            field=models.IntegerField(auto_created=True, blank=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='nonce',
            field=models.CharField(blank=True, default=0, max_length=255),
        ),
    ]
