# Generated by Django 2.0.1 on 2018-01-17 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0009_auto_20180116_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='timestamp',
            new_name='time_stamp',
        ),
    ]
