# Generated by Django 2.0.1 on 2018-01-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0010_auto_20180117_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='data',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
